config/routes.rb
Rails.application.routes.draw do
  root 'index#index'

  devise_for :staffs, controllers: { sessions: 'staffs/sessions' }
  devise_for :clients, controllers: { sessions: 'clients/sessions' }

  namespace :staffs do
    get '/', to: 'index#index', as: :root
    scope constraints: ->(req) { req.format == :json } do
      get '/user', to: 'index#user', as: :user
      resources :clients do
        collection do
          post 'verify_uniqueness'
        end
        get :organizations, on: :member, to: 'clients_organizations#organizations'
        post :organizations, on: :member, to: 'clients_organizations#add_organization'
      end
      resources :organizations, only: %i[index create show update destroy] do
        get :clients, on: :member, to: 'clients_organizations#clients'
        post :clients, on: :member, to: 'clients_organizations#add_client'
      end
      resources :staffs, only: %i[index create show update]
      resources :equipment, only: %i[index create show update] do
        collection do
          resources :types, controller: 'type_equipments', only: %i[index]
        end
      end
    end
    get '/*slug', to: 'index#index'
  end

  namespace :clients do
    get '/', to: 'index#index', as: :root
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :clients_organizations
  has_many :organizations, through: :clients_organizations

  validates :fullname, presence: true, length: { minimum: 5 }
  validates :phone, presence: true, numericality: { only_integer: true }
  validates :phone, uniqueness: true

  def valid_uniqueness?
    valid?
    errors[:email].blank? && errors[:phone].blank?
  end
end

app/models/clients_organization.rb
class ClientsOrganization < ApplicationRecord
  belongs_to :client
  belongs_to :organization
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  belongs_to :type_equipment
  belongs_to :organization

  validates :name, presence: true
  validates :serial_number, presence: true
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :equipments
  has_many :clients_organizations
  has_many :clients, through: :clients_organizations

  validates :name, presence: true
  validates :kind, presence: true
  validates :inn, presence: true, numericality: { only_integer: true }
  validates :ogrn, presence: true, numericality: { only_integer: true }
end

app/models/staff.rb
class Staff < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :fullname, presence: true, length: { minimum: 5 }
end

app/models/type_equipment.rb
class TypeEquipment < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  devise_group :user, contains: %i[staff client]

  def after_sign_in_path_for(resource)
    send("#{resource.class.to_s.downcase.pluralize}_root_path")
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index; end
end

app/controllers/staffs/base_controller.rb
class Staffs::BaseController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :respond_with_not_found

  before_action :authenticate_staff!

  protected

  def respond_with_validation_error(model, errors = nil)
    render_error :unprocessable_entity,
                 message: "Validation failed",
                 errors: (errors || model.errors)
  end

  def render_error(status, resource = nil)
    render status: status,
           json: (resource || { message: "error" })
  end

  def respond_with_not_found(exception)
    render_error :not_found,
                 name: "Not found",
                 message: exception.message
  end
end

app/controllers/staffs/index_controller.rb
class Staffs::IndexController < Staffs::BaseController
  layout 'staffs'

  def index; end

  def user
    render json: StaffSerializer.new(current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients/index_helper.rb
module Clients::IndexHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/staffs/base_helper.rb
module Staffs::BaseHelper
end

app/helpers/staffs/clients_helper.rb
module Staffs::ClientsHelper
end

app/helpers/staffs/equipment_helper.rb
module Staffs::EquipmentHelper
end

app/helpers/staffs/index_helper.rb
module Staffs::IndexHelper
end

app/helpers/staffs/organizations_helper.rb
module Staffs::OrganizationsHelper
end

app/helpers/staffs/staffs_helper.rb
module Staffs::StaffsHelper
end

app/views/index/index.html.erb
<div class="container">
  <h1>Index#index</h1>
  <p>Find me in app/views/index/index.html.erb</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrmSc</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/navigation' %>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/layouts/staffs.html.slim
doctype html
html
  head
    title Crm | Staff
    = csrf_meta_tags
    = csp_meta_tag


  body
    div class="container"
      = yield
    = javascript_pack_tag 'staffs'
    = stylesheet_pack_tag 'staffs'

app/views/shared/_navigation.html.slim
div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm"
  h5 class="my-0 mr-md-auto font-weight-normal"
    = link_to 'Service Center', root_path
  nav class="my-2 my-md-0 mr-md-3"
    ul class="nav"
      - if staff_signed_in?
        li class="nav-item"
          = link_to 'Staffs', staffs_root_path, class: "nav-link"
        li class="nav-item"
          a class="nav-link disabled" href="#" Hello Staff
        li class="nav-item"
          = link_to 'Sign out', destroy_staff_session_path, class: "nav-link"
      - elsif client_signed_in?
        li class="nav-item"
          = link_to 'Clients', clients_root_path, class: "nav-link"
        li class="nav-item"
          a class="nav-link disabled" href="#" Hello Client
        li class="nav-item"
          = link_to 'Sign out', destroy_client_session_path, class: "nav-link"
      - else
        li class="nav-item"
          = link_to 'Login as Staff', new_staff_session_path, class: 'btn btn-outline-primary ml-1'
        li class="nav-item"
          = link_to 'Login as Client', new_client_session_path, class: 'btn btn-outline-success ml-1'